// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fsutil

import (
	"sync"
)

// tempFileMock is a mock implementation of tempFile.
//
//	func TestSomethingThatUsestempFile(t *testing.T) {
//
//		// make and configure a mocked tempFile
//		mockedtempFile := &tempFileMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			WriteFunc: func(p []byte) (int, error) {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedtempFile in code that requires tempFile
//		// and then make assertions.
//
//	}
type tempFileMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// WriteFunc mocks the Write method.
	WriteFunc func(p []byte) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// P is the p argument value.
			P []byte
		}
	}
	lockClose sync.RWMutex
	lockWrite sync.RWMutex
}

// Close calls CloseFunc.
func (mock *tempFileMock) Close() error {
	if mock.CloseFunc == nil {
		panic("tempFileMock.CloseFunc: method is nil but tempFile.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedtempFile.CloseCalls())
func (mock *tempFileMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *tempFileMock) Write(p []byte) (int, error) {
	if mock.WriteFunc == nil {
		panic("tempFileMock.WriteFunc: method is nil but tempFile.Write was just called")
	}
	callInfo := struct {
		P []byte
	}{
		P: p,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(p)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedtempFile.WriteCalls())
func (mock *tempFileMock) WriteCalls() []struct {
	P []byte
} {
	var calls []struct {
		P []byte
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
